#pragma once

enum device_state_t {
	DEVICE_STATE_GLOWSTICK_GREEN,
	DEVICE_STATE_GLOWSTICK_PURPLE,
	DEVICE_STATE_GLOWSTICK_LIME,
	DEVICE_STATE_GLOWSTICK_BLUE,
	DEVICE_STATE_GLOWSTICK_RED,
	DEVICE_STATE_GLOWSTICK_WHITE,
	DEVICE_STATE_GLOWSTICK_BLAST,
	DEVICE_STATE_SWING_MODE,
	DEVICE_STATE_OSC_SWING_MODE
};

extern volatile enum device_state_t device_state;

void next_device_state(void);