[platformio]
default_envs = xiao_c6_test
src_dir = src

[env:xiao_c6_test]
platform = espressif32@7.0.1
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
upload_port = /dev/ttyACM0
upload_protocol = esptool
build_unflags = -fuse-cxa-atexit
build_flags =
	-D CONFIG_IDF_TARGET_ESP32C6=1
	-D BNO_BUTTON_TEST=1
platform_packages = platformio/toolchain-riscv32-esp @ 15.2.0+20251204
